coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        only_pulls: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true

ignore:
  - "examples/**/*"
  - "cmd/**/*" 