linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - godot
    - gofmt
    - goimports
    - gosec
    - misspell
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/parsilver/event
  govet:
    enable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
    - path: examples/
      linters:
        - all
  
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

run:
  timeout: 5m 